services:
  api:
    container_name: nginx-lua-api
    build: .
    ports:
      - "8080:80"
    environment:
      - SITE_URL=http://localhost:8080
    volumes:
      - ./api:/todoapp/api
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
  test:
    build: tests
    volumes:
       - ./tests:/tests
    depends_on:
      - api
    links:
      - api
    command: pytest /tests/tests.py