services:
  api:
    container_name: nginx-lua-api
    build: .
    ports:
      - "8080:8080"
    environment:
      - SITE_URL=http://localhost:8080
      - PORT=8080
    volumes:
      - ./api:/todoapp/api
  test:
    build: tests
    volumes:
       - ./tests:/tests
    depends_on:
      - api
    links:
      - api
    command: pytest /tests/tests.py